
export const DELETE_POST = 'POST/DELETE_POST'
export const FETCH_POSTS = 'POST/FETCH_POSTS'
export const REQUEST_POSTS = 'POST/REQUEST_POSTS'

export const REQUEST_TRANSLATOR = 'POST/REQUEST_TRANSLATOR'
export const FETCH_TRANSLATOR = 'POST/FETCH_TRANSLATOR'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'

export const REQUEST_LANGUAGE  = 'LANGUAGE/REQUEST_LANGUAGE'
export const FETCH_LANGUAGE = 'LANGUAGE/FETCH_LANGUAGE'
export const SELECTED_LANGUAGE = 'LANGUAGE/SELECTED_LANGUAGE'

export const THUMB_UP = 'POST/THUMB_UP'
export const THUMB_DOWN = 'POST/THUMB_DOWN'





